2018-01-15 23:34:30 test.py              [line:272] INFO =========================
2018-01-15 23:34:30 send_command.py      [line:11 ] INFO send command :dir
2018-01-15 23:34:31 send_command.py      [line:16 ] INFO output: 
 Volume in drive E is New Volume
 Volume Serial Number is 3EE4-D50D

 Directory of E:\python_project

01/14/2018  11:08 PM    <DIR>          .
01/14/2018  11:08 PM    <DIR>          ..
01/14/2018  10:38 PM               375 .project
01/14/2018  10:38 PM               307 .pydevproject
01/14/2018  10:41 PM    <DIR>          .settings
01/14/2018  10:39 PM    <DIR>          config
01/15/2018  11:33 PM    <DIR>          lib
01/15/2018  11:33 PM    <DIR>          result
01/15/2018  11:34 PM             6,939 test.py
01/14/2018  11:06 PM                 0 __init__.py
               4 File(s)          7,621 bytes
               6 Dir(s)  16,504,401,920 bytes free

2018-01-15 23:34:31 send_command.py      [line:42 ] INFO find .project successfully.
2018-01-15 23:34:31 test.py              [line:275] INFO get string 
01/14/
2018-01-15 23:34:31 send_command.py      [line:26 ] INFO find config successfully.
2018-01-15 23:34:31 send_command.py      [line:11 ] INFO send command :ls
2018-01-15 23:34:31 send_command.py      [line:16 ] INFO output: 
__init__.py
config
lib
result
test.py

2018-01-15 23:34:31 send_command.py      [line:22 ] INFO can not find log.py
